name: ActionForge Harness

on:
  pull_request:
  push:
    branches: [main]

jobs:
  harness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - name: Start example endpoint
        run: |
          node examples/basic-action-endpoint/dist/server.js &
          sleep 2
      - name: Run harness
        run: |
          npm exec -- actionforge-harness run --endpoint http://127.0.0.1:3001 --fixtures packages/harness/fixtures
